title: shishun's Homepage
page-top-title: Shi-Shun Chen
top-section-bg-text: Welcome to my homepage!
home-subtitle: Shi-Shun Chen&ensp;|&ensp;陈世舜
copyright-text: '&copy; Shi-Shun Chen 2025. All Rights Reserved.'
